version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: spe_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: soloparaentendidos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: spe_redis
    restart: unless-stopped

  api:
    build: 
      context: ../
      dockerfile: backend/api-spe/Dockerfile
    container_name: spe_api
    restart: unless-stopped
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/soloparaentendidos?schema=public
      - NODE_ENV=production
    ports:
      - "17000:17000"

  frontend:
    build:
      context: ../
      dockerfile: frontend/web-spe/Dockerfile.frontend
    container_name: spe_frontend
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "8080:80"

  # El Tubo Mágico de Cloudflare
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: spe_tunnel
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - frontend

volumes:
  postgres_data:
