# Dockerfile.frontend para Nginx (Compilado en Host por deploy.sh)

FROM nginx:alpine

# Copiar los estáticos YA COMPILADOS en el host (dist/)
COPY dist /usr/share/nginx/html

# Reemplazar la configuración por defecto de Nginx con la nuestra
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Exponer puerto 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
